AllCops:
  Exclude:
    - gemfiles/*
  TargetRubyVersion: 2.3
Metrics/AbcSize:
  Exclude:
    - test/**/*
Metrics/LineLength:
  Exclude:
    - test/**/*
Style/Documentation:
  Exclude:
    - test/**/*
