source "http://rubygems.org"

gem "activesupport", "~>3.0.0.rc"
gem "bundler", "~>1.0.0.rc.3"
gem "curb"
gem "jeweler"
gem "looksee"
gem "nokogiri"
gem "rake"
gem "rspec", "~>2.0.0.beta.19"
gem "wirble"
